In [1]:
import numpy as np

In [2]:
y_val = np.linspace(-0.08, 0.34, 10)
object_position_0 = [0.342, y_val[0], 0.03, 176.37, 1.04, 175.96]
object_position_1 = [0.342, y_val[1], 0.03, 176.37, 1.04, 175.96]
object_position_2 = [0.342, y_val[2], 0.03, 176.37, 1.04, 175.96]
object_position_3 = [0.342, y_val[3], 0.03, 176.37, 1.04, 175.96]
object_position_4 = [0.342, y_val[4], 0.03, 176.37, 1.04, 175.96]
object_position_5 = [0.342, y_val[5], 0.03, 176.37, 1.04, 175.96]
object_position_6 = [0.342, y_val[6], 0.03, 176.37, 1.04, 175.96]
object_position_7 = [0.342, y_val[7], 0.03, 176.37, 1.04, 175.96]
object_position_8 = [0.342, y_val[8], 0.03, 176.37, 1.04, 175.96]
object_position_9 = [0.342, y_val[9], 0.03, 176.37, 1.04, 175.96]
intermediate_position = [0.419, 0.106, 0.237, 175.84, -0.094, 176.09]
dropoff_position = [0.596, 0.093, 0.23, 175.90, -0.241, 176.13]

In [3]:
object_positions = [
    object_position_0,
    object_position_1,
    object_position_2,
    object_position_3,
    object_position_4,
    object_position_5,
    object_position_6,
    object_position_7,
    object_position_8,
    object_position_9
]
object_positions = np.array(object_positions)


In [8]:
object_positions[:, 1]

array([-0.08      , -0.03333333,  0.01333333,  0.06      ,  0.10666667,
        0.15333333,  0.2       ,  0.24666667,  0.29333333,  0.34      ])

In [9]:
expert_data = []
for i in range(10):
    data = np.load("demos/recording_%i.npy" % i)
    expert_data.append(data)
expert_data = np.array(expert_data)


In [21]:
# np.argmin(expert_data[0, :, 2])
expert_data[0, 85, :3]

array([ 0.3418237 , -0.07996723,  0.0295197 ])

In [12]:
np.save("data/expert_actions.npy", expert_data)

In [27]:
hammer_positions = []
for i in range(10):
    idx = np.argmin(expert_data[i, :, 2])
    hammer_positions.append(expert_data[i, idx, :3])
hammer_positions = np.array(hammer_positions)

In [28]:
hammer_positions

array([[ 0.3418237 , -0.07996723,  0.0295197 ],
       [ 0.34180659, -0.03330576,  0.02952183],
       [ 0.34177101,  0.01335181,  0.02953066],
       [ 0.34177741,  0.05998041,  0.0295044 ],
       [ 0.34180236,  0.10660422,  0.02951736],
       [ 0.34181589,  0.15321629,  0.02953411],
       [ 0.34185705,  0.19983071,  0.02950482],
       [ 0.34185117,  0.24657273,  0.02950849],
       [ 0.34184158,  0.24652727,  0.02952193],
       [ 0.3418847 ,  0.29320058,  0.02950581]])

In [30]:
np.save("data/hammer_positions.npy", hammer_positions)

In [26]:
hammer_positions = []
hammer_positions.append(object_position_0[:3])
hammer_positions.append(object_position_1[:3])
hammer_positions.append(object_position_2[:3])
hammer_positions.append(object_position_3[:3])
hammer_positions.append(object_position_4[:3])
hammer_positions.append(object_position_5[:3])
hammer_positions.append(object_position_6[:3])
hammer_positions.append(object_position_7[:3])
hammer_positions.append(object_position_8[:3])
hammer_positions.append(object_position_9[:3])
hammer_positions = np.array(hammer_positions)
hammer_positions

array([[ 0.342     , -0.08      ,  0.03      ],
       [ 0.342     , -0.03333333,  0.03      ],
       [ 0.342     ,  0.01333333,  0.03      ],
       [ 0.342     ,  0.06      ,  0.03      ],
       [ 0.342     ,  0.10666667,  0.03      ],
       [ 0.342     ,  0.15333333,  0.03      ],
       [ 0.342     ,  0.2       ,  0.03      ],
       [ 0.342     ,  0.24666667,  0.03      ],
       [ 0.342     ,  0.29333333,  0.03      ],
       [ 0.342     ,  0.34      ,  0.03      ]])